### PR TITLE
Add 2.15 release

### PR DESCRIPTION
**Pull request by QiuSimons**

### CODE REVIEW

**Review by 1715173329 — COMMENTED** [review]
This broken the compilation on kernel 4.15 / 4.19 at least.
Build log:
```
make -C /lib/modules/4.15.0-143-generic/build M=/home/ubuntu/realtek-r8152-linux modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-143-generic'
  CC [M]  /home/ubuntu/realtek-r8152-linux/r8152.o
/home/ubuntu/realtek-r8152-linux/r8152.c: In function ‘r8156_eee_en’:
/home/ubuntu/realtek-r8152-linux/r8152.c:5252:13: error: ‘MDIO_EEE_2_5GT’ undeclared (first use in this function); did you mean ‘MDIO_EEE_10GT’?
   config |= MDIO_EEE_2_5GT;
             ^~~~~~~~~~~~~~
             MDIO_EEE_10GT
/home/ubuntu/realtek-r8152-linux/r8152.c:5252:13: note: each undeclared identifier is reported only once for each function it appears in
/home/ubuntu/realtek-r8152-linux/r8152.c: In function ‘rtl8152_set_speed’:
/home/ubuntu/realtek-r8152-linux/r8152.c:9005:19: error: ‘MDIO_AN_10GBT_CTRL_ADV2_5G’ undeclared (first use in this function); did you mean ‘MDIO_AN_10GBT_CTRL_ADV10G’?
    new1 = orig & ~MDIO_AN_10GBT_CTRL_ADV2_5G;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
                   MDIO_AN_10GBT_CTRL_ADV10G
/home/ubuntu/realtek-r8152-linux/r8152.c: In function ‘rtl8152_get_link_ksettings’:
/home/ubuntu/realtek-r8152-linux/r8152.c:17996:41: error: ‘MDIO_AN_10GBT_CTRL_ADV2_5G’ undeclared (first use in this function); did you mean ‘MDIO_AN_10GBT_CTRL_ADV10G’?
      ocp_reg_read(tp, OCP_10GBT_CTRL) & MDIO_AN_10GBT_CTRL_ADV2_5G);
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                         MDIO_AN_10GBT_CTRL_ADV10G
/home/ubuntu/realtek-r8152-linux/r8152.c:18034:14: error: ‘MDIO_AN_10GBT_STAT_LP2_5G’ undeclared (first use in this function); did you mean ‘MDIO_AN_10GBT_STAT_LP10G’?
       data & MDIO_AN_10GBT_STAT_LP2_5G);
              ^~~~~~~~~~~~~~~~~~~~~~~~~
              MDIO_AN_10GBT_STAT_LP10G
scripts/Makefile.build:340: recipe for target '/home/ubuntu/realtek-r8152-linux/r8152.o' failed
make[2]: *** [/home/ubuntu/realtek-r8152-linux/r8152.o] Error 1
Makefile:1591: recipe for target '_module_/home/ubuntu/realtek-r8152-linux' failed
make[1]: *** [_module_/home/ubuntu/realtek-r8152-linux] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-143-generic'
Makefile:24: recipe for target 'modules' failed
make: *** [modules] Error 2
```

Update: compiles on kernel 5.4
Update: Resolved by adding missing macros (no runtime test):
```patch
diff --git a/compatibility.h b/compatibility.h
index 4bc2b63..bbf501b 100644
--- a/compatibility.h
+++ b/compatibility.h
@@ -38,6 +38,10 @@
 	# define fallthrough                    do {} while (0)  /* fallthrough */
 	#endif
 
+	#define MDIO_EEE_2_5GT				0x0001	/* 2.5GT EEE cap */
+#if LINUX_VERSION_CODE < KERNEL_VERSION(5,1,0)
+	#define MDIO_AN_10GBT_CTRL_ADV2_5G		0x0080	/* Advertise 2.5GBASE-T */
+	#define MDIO_AN_10GBT_STAT_LP2_5G		0x0020  /* LP is 2.5GBT capable */
 #if LINUX_VERSION_CODE < KERNEL_VERSION(5,0,0)
 #if LINUX_VERSION_CODE < KERNEL_VERSION(4,20,0)
 #if LINUX_VERSION_CODE < KERNEL_VERSION(4,12,0)
@@ -549,6 +553,7 @@
 		skb->next = NULL;
 	}
 #endif /* LINUX_VERSION_CODE < KERNEL_VERSION(5,0,0) */
+#endif /* LINUX_VERSION_CODE < KERNEL_VERSION(5,1,0) */
 #endif /* LINUX_VERSION_CODE < KERNEL_VERSION(5,4,0) */
 #endif /* LINUX_VERSION_CODE < KERNEL_VERSION(5,6,0) */
 #endif /* LINUX_VERSION_CODE < KERNEL_VERSION(5,9,0) */
```
